version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

  rust:
    build: .
    command: cargo run
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db/mydb"

